camunda.bpm.client:
  base-url: http://localhost:8090/engine-rest
  lock-duration: 10000
  async-response-timeout: 30000
  worker-id: rnschk

logging.level.org.camunda.bpm.client: debug

de:
  viadee:
    bpm:
      camunda:
        external-task:
          retry-config:
            default-behavior: R5/PT1M
